/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#a6feea",
        "tertiary": "#295fa7",
        "tertiary-container": "#92baff",
        "on-secondary-fixed-variant": "#007060",
        "error-container": "#f56965",
        "on-secondary": "#e3fff6",
        "secondary": "#006c5d",
        "background": "#fbf9f5",
        "on-secondary-fixed": "#005045",
        "on-error": "#fff7f6",
        "error": "#ac3434",
        "surface-container-high": "#e9e8e3",
        "surface-variant": "#e3e3dd",
        "secondary-fixed-dim": "#98f0dc",
        "inverse-primary": "#fd898a",
        "error-dim": "#70030f",
        "primary-fixed-dim": "#ff9695",
        "on-tertiary-container": "#00366e",
        "surface-container": "#efeee9",
        "surface-container-low": "#f5f3ef",
        "surface-container-highest": "#e3e3dd",
        "on-primary-fixed": "#540710",
        "outline": "#7a7b76",
        "surface-bright": "#fbf9f5",
        "on-surface-variant": "#5e605b",
        "tertiary-fixed": "#92baff",
        "on-tertiary-fixed": "#002046",
        "on-primary-fixed-variant": "#7d272b",
        "primary-container": "#ffaba9",
        "inverse-on-surface": "#9e9d99",
        "primary-fixed": "#ffaba9",
        "inverse-surface": "#0e0e0d",
        "on-secondary-container": "#006456",
        "primary-dim": "#8f3538",
        "on-surface": "#31332f",
        "on-primary-container": "#711e23",
        "on-primary": "#fff7f6",
        "on-tertiary-fixed-variant": "#003f7e",
        "on-tertiary": "#f8f8ff",
        "secondary-container": "#a6feea",
        "on-error-container": "#65000b",
        "surface-tint": "#9f4043",
        "surface": "#fbf9f5",
        "tertiary-fixed-dim": "#7dacfa",
        "tertiary-dim": "#18539a",
        "on-background": "#31332f",
        "surface-dim": "#dadad4",
        "secondary-dim": "#005e51",
        "primary": "#9f4043",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#b2b2ad"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "spaceGrotesk": ["Space Grotesk", "sans-serif"],
        "notoSerif": ["Noto Serif", "serif"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}